### ISSUE TITLE
allow-empty ?

### ISSUE THREAD

**Issue by hugolpz** [mbostock/topojson#217]
Hello, I find the following confusing : 

In the [API](https://github.com/mbostock/topojson/wiki/Command-Line-Reference)
   
 * **--filter** preserve null or empty features (e.g., zero-area polygons)

In the [Release note](https://github.com/mbostock/topojson/wiki/Release-Notes) :
 
 * **--allow-empty** command-line flag to retain null or empty features in the generated topology. As before, these features are removed by default.

Naturally,  **--allow-empty** is not in the API, and  **--filter** is not in the release note. Are them the same and which to use ?

**Comment by mbostock** [comment]
Oops, that wiki page old. You should be looking at the [list of releases](https://github.com/mbostock/topojson/releases) instead, where you will see that the 1.5 release deprecated --allow-empty in favor of --filter=none.
