### ISSUE TITLE
.data([mesh(json, json.objects.something, function(a,b){...})])

### ISSUE THREAD

**Issue by hugolpz** [mbostock/topojson#218]
Is it the expected behavior that : 

```javascript
d3.json("./admin_0.topo.json", function(error, json) { 
    var L0 =  json.objects.admin_0;
//inland borders lines
    svg.append("g").attr("id","border")
        .attr("style", mesh)
    .selectAll("path")
        .data([topojson.mesh(json, L0, function(a, b) { return a !== b; })]) // (!)
    .enter().append("path")
        .attr("d", path);
});
```

produces:

![2015 01 30_wikiatlas_wild_lines](https://cloud.githubusercontent.com/assets/1420189/5976457/4e30ad2a-a88e-11e4-8842-5434d4421622.png)

I'am aware mesh returns a single MultiLineString:

```javascript
{                                 
 type: "MultiLineString", 
 coordinates: [  
     […], // this is an arc, contains points [ lat,lon ]
     […], //many more
 ]
} 
```
Yet, shouldn't the successful (!) projection be a set of closed svg paths ? (without these artifacts)

**Comment by hugolpz** [comment]
To close or delete. Bug due to `style="stroke-dasharray:4,4;". My apologizes.

**Comment by mbostock** [comment]
FYI: https://code.google.com/p/chromium/issues/detail?id=364866

**Comment by hugolpz** [comment]
Reporting back on chromium bug tracker.
