### ISSUE TITLE
-p option does not work on Windows

### ISSUE THREAD

**Issue by aborruso** [mbostock/topojson#221]
Hi,
yesterday I have installed topojson 1.6.18 on Windows. When I use -p option I have no attributes in json file output.

I have used this command:
topojson input.shp -o output.json -p

Here my input and output files: http://ge.tt/9P6uK5A2?c

Is it normal?

Thank you

**Comment by kwoxer** [comment]
You already tried it like this?

topojson -p -o "map.json" "layer.json"

**Comment by mbostock** [comment]
Unable to reproduce. I ran the following command using the contents of the provided input.zip, and the resulting JSON contained properties:

```bash
topojson 'com2011_g simplified (4).shp' -o output.json -p
```

It seems risky to have spaces and parentheses in your file names, though, so you might try renaming your files to make sure something else weird isn’t happening.

**Comment by mbostock** [comment]
(I should mention that I did this on OS X rather than Windows, but I do not run Windows and cannot provide support for it. Sorry!)

**Comment by kwoxer** [comment]
But I have Windows and the command above from me runs well =)

Windows 8 64bit

**Comment by aborruso** [comment]
It's a sort of a miracle: now the same command (with the same input file) works.

Thank you for all your work, I feel myself stupid :(

**Comment by kwoxer** [comment]
Happens to anymore. =)
