### ISSUE TITLE
Hangs starting at v1.6

### ISSUE THREAD

**Issue by lucastimmons** [mbostock/topojson#222]
Running OS X 10.10.1 on a mid 2013 Macbook air, with node v0.10.36 and npm v2.5.0.

Running topojson v1.5.4 in the terminal gives the expected usage and version details. 

Using any version from 1.6 on does nothing. It starts and no commands other than quitting node are accepted. No version or usage is displayed. 

Not sure how long this has been an issue, just got a new computer with Yosemite. I've installed 1.5.4 via NPM. Not sure what's causing this, or if anyone else is having the same issue.

**Comment by jasondavies** [comment]
I think this is expected behaviour as of [version 1.6.6](https://github.com/mbostock/topojson/releases/tag/v1.6.6): if no input files are specified it will attempt to read from stdin rather than print usage information.  You can still print usage information via `topojson --help`.

**Comment by mbostock** [comment]
Yep, this is the standard behavior for programs that read from stdin by default.
