### ISSUE TITLE
Options behaviour (--properties) doesn't match documentation

### ISSUE THREAD

**Issue by stevage** [mbostock/topojson#223]
According to the documentation:
```
Usage: topojson [options] [file …]
...
  -p, --properties               feature properties to preserve; no name preserves all properties             [default: false]
```

So this should work: `topojson --properties input.geojson`

But it doesn't. `input.geojson` gets parsed as a property name to preserve and topojson hangs waiting for input. You have to do this:

`topojson input.geojson --properties`

**Comment by mbostock** [comment]
You should use `--` to separate the [file …] part from the [options] part, like so:

```bash
topojson --properties -- input.geojson
```

This is standard behavior for command-line arguments, which is why it wasn’t explicitly mentioned in the documentation. I have now added it to the wiki and the usage with `topojson --help`.

**Comment by stevage** [comment]
Ah yep, makes sense - thanks.
