### ISSUE TITLE
Arcs vs. Coordinates

### ISSUE THREAD

**Issue by mishawagon** [mbostock/topojson#255]
I had a problem with D3 choking on "arcs" in topojson file but works with "coordinates" in geojson file. Has anyone had that issue?

**Comment by mbostock** [comment]
You need to convert TopoJSON to GeoJSON using the TopoJSON client library before you can render with D3; D3 doesn’t render TopoJSON directly.

**Comment by mishawagon** [comment]
Ah, and I see that I can do the translation client side with the topojson library. Thank you sir!
