### ISSUE TITLE
incompatibility with ng-annotate

### ISSUE THREAD

**Issue by diegopamio** [mbostock/topojson#268]
Latest release 1.6.20 brings incompatibility with ng-annotate 1.2.1

**Comment by mbostock** [comment]
There is insufficient information here to investigate; I don’t maintain ng-annotate, so I don’t know why it would stop working.

**Comment by jteppinette** [comment]
1.16.20 killed my build sooo...

Karma was giving an error "can't reference variable module"

The problem was by all of the topojson = module.exports = require.... etc...

**Comment by mbostock** [comment]
Sorry, but that’s still insufficient information to investigate.
