### ISSUE TITLE
Latest patch release (1.6.21) should be a major release; causes breaking changes.

### ISSUE THREAD

**Issue by alatzl** [mbostock/topojson#269]
#265 is a breaking change. According to semver, this should be released with a major version bump, not a patch-level update.

The latest release of topojson causes breaking changes if installing via bower (the /build folder is never created). Anyone who has installed this package with bower now faces failing builds and/or must update their own dependencies to an older version of topojson. 

Can you release another patch-level version with those changes reverted? Then the changes from #265 can be released with a major version.

**Comment by mbostock** [comment]
I removed support for Bower because I’m tired of managing generated files in the git repository, and Bower doesn’t support publishing generated files. Unfortunately, there’s no way to stop publishing new versions to Bower. So, my only option is to unregister it from Bower entirely. Do you want me to do that?

**Comment by mbostock** [comment]
Also, I don’t consider this a breaking change from a semver perspective. (Yes, it breaks Bower, but only because I can’t stop publishing to Bower without unregistering, which also breaks Bower.) As I wrote in #267:

> I apologize for the inconvenience, but I do not consider the names of the source files in the git repository to be part of the public API. The public entry point is defined by the “main” entry in the package.json file when using CommonJS (e.g., Node), or the “browser” entry when using Browserify.
>
> In other environments, the location of the UMD bundle is at your discretion. You can build the bundle yourself, or you can access the bundle from the npm registry, the GitHub release, the hosted copy on d3js.org, or a CDN of your choice.

**Comment by jkjustjoshing** [comment]
It's a breaking change for anyone using the package with bower. Two options you've presented:
1. Implement commit 722e3e0
2. Unregister from bower entirely

but you also have another option:
3. Bump the major version to 2.0.0, and then implement 722e3e0

For those of us using the package in bower, pointed at version `~1.6.20`, options 1 and 2 break our projects, but option 3 does not. The end result is the same - you can stop supporting bower. It just doesn't violate semver guidelines (and more importantly, the build for projects using bower).

**Comment by chris-clm09** [comment]
This is unfortunate. Given that my projects use bower I would have expected a major release as well.

**Comment by mbostock** [comment]
How does bumping the version to 2.0 help? Installing version 2.0 on Bower will still be broken.

**Comment by alatzl** [comment]
Installing 2.0 on Bower would be broken in the suggested Option 3. But any project with "~1.6.19"  would not longer break by default; it would require a conscious change on the developer's part to specify a "~2.0.0" version dependency (or "*", if you want latest and greatest all the time).

**Comment by jkjustjoshing** [comment]
The issue is that a repository that worked yesterday, that I literally changed nothing with, doesn't work today. The point of semver is that you can specify a major and minor version and trust that day-to-day nothing will break as patch releases are released, as long as the use of the package is "as advertised". This patch version broke this trust.

**Comment by jkjustjoshing** [comment]
(also, regarding #267, you honestly should have bumped the major version there as well - if the file is present in `node_modules/topojson` when running `npm install topojson`, I expect them to only change with a major release bump)

**Comment by mbostock** [comment]
As I’ve already stated, the names of the source files in the git repository weren’t part of the public API, and changes to the public API were backwards-compatible.

I suppose I could repoint Bower at a different repository containing the generated files, and then setup an automated process to copy the generated files from this repository, as [bower-chosen](https://github.com/harvesthq/bower-chosen) does.

**Comment by jkjustjoshing** [comment]
Sure, you could do that, but wouldn't bumping the major version number be easier? In the long run it would be no different from leaving things as they are.

**Comment by mbostock** [comment]
Bumping the major version number is a pain for everyone else that is not affected by Bower. Also, bumping the major version number would still make `bower install topojson` broken.

**Comment by jkjustjoshing** [comment]
Eh, not really a pain. What's currently working will still work for them, and if they want new features/bugfixes they can bump the version they're including in `package.json`. Not too much of a pain (especially compared to a project's build breaking for no apparent reason).

Here's how @bendrucker, who has several packages at medium adoption levels, approached this - https://twitter.com/bendrucker/status/605855408247312384

**Comment by mbostock** [comment]
Okay, I’ve repointed topojson at [topojson-bower](https://github.com/mbostock/topojson-bower). I back-filled all the old release tags, so it should work with all versions. Let me know if that works for you.

**Comment by jkjustjoshing** [comment]
Thanks! :)

**Comment by alatzl** [comment]
Much appreciated. =)

**Comment by mbostock** [comment]
Sorry for all the hassle!

**Comment by chris-clm09** [comment]
Thank you!
