### ISSUE TITLE
In bower.json / package.json, ignore is missing

### ISSUE THREAD

**Issue by PikachuEXE** [mbostock/topojson#272]
I just upgraded from 1.6.20 => 1.6.21
It seems the bower.json file is gone, and now the ignore node is missing
So I got a lot of useless files

Is this a mistake or on purpose?

**Comment by mbostock** [comment]
duplicate of #273

**Comment by PikachuEXE** [comment]
I guess this one is about all the extra files I am getting, including the test files
So unless those files are all related to #273, including test files, I don't think this is a duplicate to #273

**Comment by mbostock** [comment]
Please read my response there.
