### ISSUE TITLE
How to use 1.6.21 in browser?

### ISSUE THREAD

**Issue by PikachuEXE** [mbostock/topojson#273]
Before I only load the script in browser directly.
Now the file `topojson.js` is gone and I am not sure how to use this lib anymore.

**Comment by mbostock** [comment]
Sounds like you may need to clear your Bower cache. Due to Bower’s design, it is not capable of storing published generated files outside the git repository. Therefore in release 1.6.21 I moved the Bower package definition to the topojson-bower repository. If you have the old definition cached you may be seeing the non-Bower repository from the old definition.

**Comment by PikachuEXE** [comment]
OK I think I have found the repo
https://github.com/mbostock/topojson-bower

Maybe worth having a temporary notice in README

**Comment by mbostock** [comment]
If you want the generated file (outside of Bower), see the downloads attached to the latest release, or npm install, or use the hosted copy on d3js.org.

**Comment by PikachuEXE** [comment]
Thanks.
I am using Bower and specifying `"topojson": ">= 1.6.18"`
Not sure why it gives me the files in this repo
I will try again next week

**Comment by mbostock** [comment]
The installation instructions are covered in the [API Reference](https://github.com/mbostock/topojson/wiki/API-Reference#client-api). I’ve updated them to point to the above referenced sources.

**Comment by mbostock** [comment]
Specifically, run `bower cache clean`. When you run `bower info topojson`, you should see something like this:

```
$ bower info topojson
bower topojson#*                cached git://github.com/mbostock/topojson-bower.git#1.6.21
bower topojson#*              validate 1.6.21 against git://github.com/mbostock/topojson-bower.git#*

{
  name: 'topojson',
  description: 'An extension to GeoJSON that encodes topology.',
  main: 'topojson.js',
  license: 'BSD-3-Clause',
  homepage: 'https://github.com/mbostock/topojson-bower',
  version: '1.6.21'
}

Available versions:
  - 1.6.21
…
```

**Comment by PikachuEXE** [comment]
Thanks for you info again :smile: 
I didn't know about `bower cache clean`
