### ISSUE TITLE
Add flowtype / typescript definition files.

### ISSUE THREAD

**Issue by vicapow** [mbostock/topojson#290]
Would there be any interest in adding seperate flowtype or typescript definitions files?

**Comment by mbostock** [comment]
It’d be great if someone wants to do it, but I don’t have the bandwidth to maintain Flow or TypeScript definition files, so I’d prefer them to live in another repository (e.g., [DefinitelyTyped](https://github.com/DefinitelyTyped/DefinitelyTyped) for TypeScript).
